### ISSUE TITLE
ihaskell-inline-r-0.1.1.0: build error on openSUSE_Tumbleweed/i586

### ISSUE THREAD

**Issue by peti** [tweag/HaskellR#258] opened 2016-08-22 08:27 UTC
Our attempts to compile ihaskell-inline-r-0.1.1.0 on 32 bit openSUSE Linux fail with the following error:

~~~~
[  156s] + ./Setup configure -v --prefix=/usr --libdir=/usr/lib --docdir=/usr/share/doc/packages/ghc-ihaskell-inline-r '--libsubdir=$compiler/$pkgkey' '--datasubdir=$pkgid' --ghc -p --enable-shared --htmldir=/usr/share/doc/ghc/html/libraries/ihaskell-inline-r-0.1.1.0 --global
[  157s] Configuring ihaskell-inline-r-0.1.1.0...
[  157s] Dependency base >=4.7 && <5: using base-4.8.2.0
[  157s] Dependency base64-bytestring -any: using base64-bytestring-1.0.0.1
[  157s] Dependency blaze-html -any: using blaze-html-0.8.1.2
[  157s] Dependency bytestring -any: using bytestring-0.10.6.0
[  157s] Dependency filepath -any: using filepath-1.4.0.0
[  157s] Dependency ihaskell -any: using ihaskell-0.8.4.0
[  157s] Dependency ihaskell-blaze -any: using ihaskell-blaze-0.3.0.0
[  157s] Dependency inline-r >=0.6.0.1: using inline-r-0.8.0.1
[  157s] Dependency template-haskell -any: using template-haskell-2.10.0.0
[  157s] Dependency temporary >=1.2: using temporary-1.2.0.4
[  157s] Using Cabal-1.22.8.0 compiled by ghc-7.10
[  157s] Using compiler: ghc-7.10.3
[  157s] Using install prefix: /usr
[  157s] Binaries installed in: /usr/bin
[  157s] Libraries installed in: /usr/lib/ghc-7.10.3/ihask_HnVrLSyQXNIGtupNZtBBxH
[  157s] Private binaries installed in: /usr/libexec
[  157s] Data files installed in: /usr/share/ihaskell-inline-r-0.1.1.0
[  157s] Documentation installed in: /usr/share/doc/packages/ghc-ihaskell-inline-r
[  157s] Configuration files installed in: /usr/etc
[  157s] No alex found
[  157s] Using ar found on system at: /usr/bin/ar
[  157s] No c2hs found
[  157s] No cpphs found
[  157s] Using gcc version 6 found on system at: /usr/bin/gcc
[  157s] Using ghc version 7.10.3 found on system at: /usr/bin/ghc
[  157s] Using ghc-pkg version 7.10.3 found on system at: /usr/bin/ghc-pkg
[  157s] No ghcjs found
[  157s] No ghcjs-pkg found
[  157s] No greencard found
[  157s] Using haddock version 2.16.1 found on system at: /usr/bin/haddock
[  157s] No happy found
[  157s] Using haskell-suite found on system at: haskell-suite-dummy-location
[  157s] Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
[  157s] No hmake found
[  157s] Using hpc version 0.67 found on system at: /usr/bin/hpc
[  157s] Using hsc2hs version 0.67 found on system at: /usr/bin/hsc2hs
[  157s] No hscolour found
[  157s] No jhc found
[  157s] Using ld found on system at: /usr/bin/ld
[  157s] No lhc found
[  157s] No lhc-pkg found
[  157s] Using pkg-config version 0.29.1 found on system at: /usr/bin/pkg-config
[  157s] Using strip version 2.26 found on system at: /usr/bin/strip
[  157s] Using tar found on system at: /bin/tar
[  157s] No uhc found
[  157s] + '[' -x Setup ']'
[  157s] + LANG=en_US.utf8
[  157s] + ./Setup build -j8 -v
[  157s] Component build order: library
[  157s] creating dist/build
[  157s] creating dist/build/autogen
[  157s] Building ihaskell-inline-r-0.1.1.0...
[  157s] /usr/bin/ghc-pkg init dist/package.conf.inplace
[  157s] Preprocessing library ihaskell-inline-r-0.1.1.0...
[  157s] Building library...
[  157s] creating dist/build
[  157s] /usr/bin/ghc --make -fbuilding-cabal-package -O -j8 -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -Idist/build/autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -this-package-key ihask_HnVrLSyQXNIGtupNZtBBxH -hide-all-packages -no-user-package-db -package-db dist/package.conf.inplace -package-id base-4.8.2.0-a3ce8575fb7e5b352e3a0df9b7b44e44 -package-id base64-bytestring-1.0.0.1-91ffab134f719cf9173a367762f52424 -package-id blaze-html-0.8.1.2-d126378da327d5387b0bc491fbd8f251 -package-id bytestring-0.10.6.0-6b1a160854b49c3effdb944774929b48 -package-id filepath-1.4.0.0-59267d26bde9029c896503f5d82794cc -package-id ihaskell-0.8.4.0-25843944ddc3f37b61e08d096236f5c8 -package-id ihaskell-blaze-0.3.0.0-ad813b450a2c83d25c5138d52ad34207 -package-id inline-r-0.8.0.1-1bec0ff1db370ad7a6f707c8e758639f -package-id template-haskell-2.10.0.0-519a3df6ca75400791d9a21bab268b67 -package-id temporary-1.2.0.4-bff44640624016639f7fc162ca2965d7 -XHaskell2010 IHaskell.Display.InlineR -Wall
[  158s] [1 of 1] Compiling IHaskell.Display.InlineR ( src/IHaskell/Display/InlineR.hs, dist/build/IHaskell/Display/InlineR.o )
[  161s] 
[  161s] src/IHaskell/Display/InlineR.hs:39:16:
[  161s]     Exception when trying to run compile-time code:
[  161s]       cast: Dynamic type cast failed. Expected: Expr. Actual: Nil.
[  161s]     Code: quoteExp
[  161s]             r " png(filename=path_hs, width=480, height=480, bg=\"white\"); "
[  161s]     In the Template Haskell quotation
[  161s]       [| withSystemTempFile "ihaskell-inline-r-.png"
[  161s]          $ \ path h
[  161s]              -> do { hClose h;
[  161s]                      _ <- [r| png(filename=path_hs, width=480, height=480, bg="white"); |];
[  161s]                      .... } |]
[  161s] error: Bad exit status from /var/tmp/rpm-tmp.MVTKiU (%build)
~~~

**Comment by mboes** [comment] 2016-08-26 18:51
What version of R are you compiling against?

**Comment by peti** [comment] 2016-08-27 10:37
We have these versions:

~~~
[  156s] [408/486] cumulate R-base-3.3.1-6.1
[  156s] [409/486] cumulate R-boot-1.3.18-6.1
[  156s] [410/486] cumulate R-codetools-0.2.14-6.1
[  156s] [411/486] cumulate R-compiler-3.3.1-6.1
[  156s] [412/486] cumulate R-datasets-3.3.1-6.1
[  157s] [413/486] cumulate R-stats4-3.3.1-6.1
[  157s] [414/486] cumulate R-core-devel-3.3.1-6.1
[  157s] [415/486] cumulate R-KernSmooth-2.23.15-6.1
[  157s] [416/486] cumulate R-MASS-7.3.45-6.1
[  157s] [417/486] cumulate R-Matrix-1.2.6-6.1
[  157s] [418/486] cumulate R-class-7.3.14-6.1
[  157s] [419/486] cumulate R-cluster-2.0.4-6.1
[  157s] [420/486] cumulate R-foreign-0.8.66-6.1
[  157s] [421/486] cumulate R-graphics-3.3.1-6.1
[  157s] [422/486] cumulate R-grid-3.3.1-6.1
[  158s] [423/486] cumulate R-lattice-0.20.33-6.1
[  158s] [424/486] cumulate R-methods-3.3.1-6.1
[  158s] [425/486] cumulate R-nlme-3.1.128-6.1
[  158s] [426/486] cumulate R-nnet-7.3.12-6.1
[  158s] [427/486] cumulate R-parallel-3.3.1-6.1
[  158s] [428/486] cumulate R-rpart-4.1.10-6.1
[  158s] [429/486] cumulate R-spatial-7.3.11-6.1
[  158s] [430/486] cumulate R-splines-3.3.1-6.1
[  158s] [431/486] cumulate R-survival-2.39.4-6.1
[  159s] [432/486] cumulate R-tools-3.3.1-6.1
[  159s] [433/486] cumulate R-utils-3.3.1-6.1
[  159s] [434/486] cumulate R-mgcv-1.8.12-6.1
[  159s] [435/486] cumulate R-stats-3.3.1-6.1
[  159s] [436/486] cumulate R-tcltk-3.3.1-6.1
~~~~

**Comment by peti** [comment] 2016-08-27 11:19
Another data point might be that it *looks* like this error occurs only on 32 bit linux. The x86_64 builds work fine. Not sure whether that helps.

**Comment by mboes** [comment] 2016-08-29 20:55
Hm, haven't tested with R-3.3 yet. It's bad news if things fail in 32-bits but not 64-bits!

**Comment by mboes** [comment] 2016-09-04 20:27
@peti if you can confirm this a 32-bits only issue then I'm tempted to close this as a wontfix and document that we don't support 32-bit systems. It's not entirely trivial to reproduce this environment since docker only supports 64 bits and recent opensuse 32 bit vm images aren't all that easy to come by. And likely it would take a lot of time to get to the bottom of this error.

**Closed by mboes** 2016-09-04 20:27 UTC

**Comment by peti** [comment] 2016-09-06 10:22
I'll remove the package from the openSUSE distribution for the time being until someone can find out what causes these failures.
