### ISSUE TITLE
nix build fails

### ISSUE THREAD

**Issue by ilikeavocadoes** [tweag/HaskellR#327] opened 2018-06-14 07:59 UTC
Output:

```
=================================== FAILURES ===================================
__________________________ TestTopdirTrash.test_trash __________________________


self = <tests.test_plat_other.TestTopdirTrash testMethod=test_trash>

    def test_trash(self):
        s2t(self.filePath)
        self.assertFalse(op.exists(self.filePath))
>       self.assertTrue(op.exists(op.join(self.trashDir, str(os.getuid()), 'files', self.fileName)))
E       AssertionError: False is not true
tests/test_plat_other.py
:115: AssertionError
====================== 1 failed, 6 passed in 0.16 seconds ======================
builder for ‘/nix/store/dbjvy671fb854dz2fqlzb8xhyqks7186-python3.6-Send2Trash-1.4.2.drv’ failed with exit code 1
killing process 3745
cannot build derivation ‘/nix/store/9hyxq7qa42q1cc3lpiv0w64c55vbifzj-python3.6-notebook-5.3.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/9hyxq7qa42q1cc3lpiv0w64c55vbifzj-python3.6-notebook-5.3.1.drv’ failed

```
Platform: Mac OS X 10.13.4
Steps to reproduce:
- Clone the repo
- Use `nix-shell`

**Comment by adamConnerSax** [comment] 2018-11-08 19:34
I'm also having issues with building using "stack --nix build" on OS X Mojave (10.14.1)
First (i) I had an issue around a dylib that (I believe) came from being on Mojave, so I chose a more recent nixpkgs commit via "nixpkgs.nix"  That was more successful in that it got to building actual haskell libs.  But that failed also, while building inline-r due to an error from hsc2hs about "Argument List Too Long":
```
--  While building package inline-r-0.9.2 using:
      /Users/adam/.stack/setup-exe-cache/x86_64-osx-nix/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-osx-nix/Cabal-2.0.1.0 build lib:inline-r --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/adam/DataScience/HaskellR/.stack-work/logs/inline-r-0.9.2.log

    Preprocessing library for inline-r-0.9.2..
    /nix/store/0xmd5y839v933rphp3c1vh9pqxj5nxyk-ghc-8.2.2/bin/hsc2hs: createProcess: runInteractiveProcess: exec: resource exhausted (Argument list too long)
```
There is some info about errors like this on the nixpkgs issues: 
[https://github.com/NixOS/nixpkgs/issues/49206](url)
but I was unable to use that to figure out a way forward.  I did try some newer commits of nixpkgs and some different versions of stack and I end up with the same issue.  

Platform: Mac OS X 10.14.1
Steps to reproduce (i):
- Clone the repo
- stack --nix build

Steps to reproduce (ii):
- Update nixpkgs commit in nixpkgs.nix to, e.g., c4c735665b6dbe4465f6f212ad7cf283027159f8
- stack --nix build

**Comment by qnikst** [comment] 2018-11-28 14:35
thanks for exact steps to reproduce, I'll try to replicate the issue

**Comment by qnikst** [comment] 2018-12-05 20:20
so I've done some research, it's not yet finished, as I'm facing other issues. But the main outcome is that `stack --nix build` puts all libraries to the command line of inline-r, even when they are not used there.
I've used following fix on CI:
```
nix-shell --run 'stack build'
```
And I was able to fix this problem, see if that can work for you. Unfortunately, I expect that it's
not a full solution, as I was getting some other errors during installation on recent nixpkgs.

**Comment by qrilka** [comment] 2018-12-10 09:37
Installation with Nix using `nix-env -f '<nixpkgs>' -iA haskellPackages.H` fails with
```
Building test suite 'test-qq' for inline-r-0.9.2..
[1 of 1] Compiling Main             ( tests/test-qq.hs, dist/build/test-qq/test-qq-tmp/Main.o )
/nix/store/9pifap75pkb9ifmdqh0irn8wgc3q38s6-stdenv-linux/setup: line 1298: 27501 Segmentation fault      ./Setup build
```

building without tests results in 

```
  Preprocessing executable 'H' for H-0.9.0.1..
  Building executable 'H' for H-0.9.0.1..
  [1 of 2] Compiling Paths_H          ( dist/build/H/autogen/Paths_H.hs, dist/build/H/H-tmp/Paths_H.o )
  [2 of 2] Compiling Main             ( H.hs, dist/build/H/H-tmp/Main.o )
  /nix/store/9pifap75pkb9ifmdqh0irn8wgc3q38s6-stdenv-linux/setup: line 1298:  8139 Segmentation fault      ./Setup build
```

Using Gentoo + unstable nixpkgs

**Comment by qnikst** [comment] 2018-12-10 10:33
Thanks for the heads up! Currently I'm trying to fix this problem but I don't have a clearly defined ETA on this issue.

**Comment by technocrat** [comment] 2019-12-27 07:38
`nix-shell --run 'stack `build` succeeded on Ubuntu 19.10, where `stack --nix build` failed. It's not finding `H` in my path yet, but that should be easy to run down.

**Comment by GregorySchwartz** [comment] 2020-06-30 17:52
I'm having an issue on a nix macOS build with `inline-r` as a dependency. I get the error

```
Preprocessing library for inline-r-0.10.2..
dyld: Library not loaded: libRblas.dylib
  Referenced from: /nix/store/pcrfz5cd31n519qxfrq3qbmv3qpzfhdp-R-4.0.0/lib/R/lib/libR.dylib
  Reason: image not found
running dist/build/Foreign/R_hsc_make failed (exit code -6)
command was: dist/build/Foreign/R_hsc_make  >dist/build/Foreign/R.hs
builder for '/nix/store/hcf6mpa4vprj92q3c0zdifi90lsam4bl-inline-r-0.10.2.drv' failed with exit code 1
```

which is weird as it somehow found `libR.dylib` which is in the same directory as `libRblas.dylib`. However, building `inline-r` itself with `stack build` from the supplied `shell.nix` works for some reason. I tried setting `DYLIB` in my `default.nix`, but that did not work either.

**Comment by idontgetoutmuch** [comment] 2020-10-02 14:53
> I'm having an issue on a nix macOS build with `inline-r` as a dependency. I get the error
> 
> ```
> Preprocessing library for inline-r-0.10.2..
> dyld: Library not loaded: libRblas.dylib
>   Referenced from: /nix/store/pcrfz5cd31n519qxfrq3qbmv3qpzfhdp-R-4.0.0/lib/R/lib/libR.dylib
>   Reason: image not found
> running dist/build/Foreign/R_hsc_make failed (exit code -6)
> command was: dist/build/Foreign/R_hsc_make  >dist/build/Foreign/R.hs
> builder for '/nix/store/hcf6mpa4vprj92q3c0zdifi90lsam4bl-inline-r-0.10.2.drv' failed with exit code 1
> ```
> 
> which is weird as it somehow found `libR.dylib` which is in the same directory as `libRblas.dylib`. However, building `inline-r` itself with `stack build` from the supplied `shell.nix` works for some reason. I tried setting `DYLIB` in my `default.nix`, but that did not work either.

I also get this error.

**Comment by idontgetoutmuch** [comment] 2020-10-05 08:05
I think we can close this issue now - I'll close it in a few days if no-one objects.

**Closed** 2020-10-14 08:30 UTC
Labels: bug
