### ISSUE TITLE
Build from git HEAD fails for GHC 8.10

### ISSUE THREAD

**Issue by erikd** [tweag/HaskellR#377] opened 2022-09-16 06:42 UTC
**Describe the bug**

First I ran into https://github.com/tweag/HaskellR/issues/374

Then trying to fix that, I cloned the repo and tried to build it and got:
```
> cabal build inline-r --minimize-conflict-set
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: inline-r-0.10.5 (user goal)
[__1] next goal: singletons-th (dependency of inline-r)
[__1] rejecting: singletons-th-3.1.1 (conflict: inline-r => singletons-th>=4)
[__1] skipping: singletons-th-3.1, singletons-th-3.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=4' from 'inline-r')
[__1] fail (backjumping, conflict set: inline-r, singletons-th)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: inline-r, singletons-th
```

**To Reproduce**
Steps to reproduce the behavior.
```
git clone https://github.com/tweag/HaskellR
cd HaskellR
# create trivial cabal.project file
cabal build inline-r --minimize-conflict-set
```

**Expected behavior**
I expect it to build

**Environment**
 - OS name + version: Debian Texting
 - Version of the code: commit c3ba1023480e26ade420896bcb629ceaad59f308
 - GHC version: 8.10.7
 - cabal version: 3.8.1.0

**Additional context**
Contents of `cabal.project`
```
packages:
  H
  IHaskell
  inline-r

test-show-details: direct
```

**Comment by idontgetoutmuch** [comment] 2022-09-16 07:15
Hi @erikd just to let you know that the principal maintainer has this

> On March 2nd, I joined the Ukrainian military (the National Guard) to play my small part in defending Ukraine.

**Comment by erikd** [comment] 2022-09-16 07:16
@idontgetoutmuch is that Roman?

**Comment by idontgetoutmuch** [comment] 2022-09-16 07:17
@erikd yes

**Comment by erikd** [comment] 2022-09-16 07:18
On Hackage, the maintainer is listed as Mathieu who I believe is French.

**Comment by andreabedini** [comment] 2022-09-16 07:34
The bounds change in 3e6b6804c419adbb53a5923149c4f6063d30d72e seem sa bit funny to me.
```diff
-                     , singletons >= 0.9 && < 3
+                     , singletons >= 3
+                     , singletons-th >= 3
```
There's no code change to warrant moving from `singletons >= 0.9` to `singletons >= 3`, and we don't need `singletons-th`.
I will see what I can do.

**Comment by erikd** [comment] 2022-09-16 07:37
I seem to recall that `singletons` (and maybe also `singletons-th`) is tightly version locked with the GHC version. Therefore I usually remove any version bounds on `singletons` and let the compiler sort it out.

**Comment by andreabedini** [comment] 2022-09-16 07:54
`singletons-th` yes (`singletons-th-3.1.1` has `base >=4.17 && <4.18`), but `singletons` seems to be more lenient (`singletons-3.0.2` has `base >=4.9 && <4.18`).

**Comment by mboes** [comment] 2022-11-01 15:42
@andreabedini gotten somewhere?

**Comment by andreabedini** [comment] 2022-11-02 00:23
@mboes We didn't end up needing to build this package at IOG so I had stopped. I will give it a second look (especially now that #379 is merged).

**Comment by mboes** [comment] 2022-11-04 01:18
@andreabedini I saw you opened #381, which creates a whole new `cabal`-based CI workflow. The issue reported here can be reproduced with either Stack or cabal-install. It's just that #366 broke building with GHC 8.10. So I extracted the minimal change from your PR that fixes the problem. It's in #384.

**Closed** 2022-11-04 18:32 UTC
