### ISSUE TITLE
libR not found (OS X)

### ISSUE THREAD

**Issue by tcfuji** [tweag/HaskellR#200] opened 2015-09-09 05:37 UTC
I'm using OS X 10.10.3 and have R 3.2.2 installed.
Getting the following:
```
$ stack build --copy-bins H
Run from outside a project, using implicit global config
Using resolver: lts-3.4 from global config file: /Users/tcf/.stack/global/stack.yaml
inline-r-0.7.0.0: configure
Progress: 1/2
--  While building package inline-r-0.7.0.0 using:
      /Users/tcf/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/tcf/.stack/snapshots/x86_64-osx/lts-3.4/7.10.2/pkgdb/ --package-db=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/pkgdb/ --libdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/lib --bindir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/bin --datadir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/share --libexecdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/libexec --sysconfdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/etc --docdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/doc/inline-r-0.7.0.0 --htmldir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/doc/inline-r-0.7.0.0 --haddockdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/doc/inline-r-0.7.0.0 --dependency=aeson=aeson-0.8.0.2-85507016086edfeeee941f8a8eed5cd2 --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=bytestring=bytestring-0.10.6.0-6e8453cb70b477776f26900f41a5e17a --dependency=data-default-class=data-default-class-0.0.1-06f131700d8043a79c55259693817561 --dependency=deepseq=deepseq-1.4.1.1-5de90d6c626db2476788444fb08c1eb3 --dependency=exceptions=exceptions-0.8.0.2-b08bd0de7dff383d124cad3f4c34eddd --dependency=mtl=mtl-2.2.1-5cf332b11edb88a6040af20fd6a58acb --dependency=pretty=pretty-1.1.2.0-1d31b75e6aa28069010db3db8ab24535 --dependency=primitive=primitive-0.6-f39f6bcba2f66e648d35c2c6a451ec07 --dependency=process=process-1.2.3.0-36e5501145ab363f58c5e5a7079e9636 --dependency=setenv=setenv-0.1.1.3-d0e7280b0b040f30ae79cbf77c845175 --dependency=singletons=singletons-1.1.2.1-79af6019e5989899d9ed1be7b4536d20 --dependency=template-haskell=template-haskell-2.10.0.0-161ca39a5ae657ff216d049e722e60ea --dependency=text=text-1.2.1.3-2395ef415c1b20175aae83b50060e389 --dependency=th-lift=th-lift-0.7.2-f47e42104ef13446a0b63c1ccb79d01e --dependency=th-orphans=th-orphans-0.12.2-5f347fc4e286f18cfa7cdecfbddd1808 --dependency=transformers=transformers-0.4.2.0-21dcbf13c43f5d8cf6a1f54dee6c5bff --dependency=unix=unix-2.7.1.0-75051e1ddce506fe76a9ea932b926357 --dependency=vector=vector-0.10.12.3-c6e124f63e87ac124e3bbb7bdf0ab89f
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/tcf/.stack/global/.stack-work/logs/inline-r-0.7.0.0.log

    Configuring inline-r-0.7.0.0...
    setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2: The pkg-config package
    'libR' version >=3.0 is required but it could not be found.
```

**Comment by Fuuzetsu** [comment] 2015-09-09 10:15
You need to make sure that GHC can find the R library during build. Did you try passing `--extra-include-dirs` to `stack build` to help it out?

**Comment by tcfuji** [comment] 2015-09-09 16:21
Which directory is required? I tried including the following:

`/Library/Frameworks/R.framework/Versions/3.2/`, `/Library/Frameworks/R.framework/Versions/3.2/Resources/`,
`/Library/Frameworks/R.framework/Versions/3.2/Resources/lib`,
`/Library/Frameworks/R.framework/Versions/3.2/Resources/lib/`

but I get the same output as above. Example: 

```
$ stack build --copy-bins H --extra-include-dirs /Library/Frameworks/R.framework/Versions/3.2/Resources/lib
Run from outside a project, using implicit global config
Using resolver: lts-3.4 from global config file: /Users/tcf/.stack/global/stack.yaml
inline-r-0.7.0.0: configure
Progress: 1/2
--  While building package inline-r-0.7.0.0 using:
      /Users/tcf/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/tcf/.stack/snapshots/x86_64-osx/lts-3.4/7.10.2/pkgdb/ --package-db=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/pkgdb/ --libdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/lib --bindir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/bin --datadir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/share --libexecdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/libexec --sysconfdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/etc --docdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/doc/inline-r-0.7.0.0 --htmldir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/doc/inline-r-0.7.0.0 --haddockdir=/Users/tcf/.stack/global/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/doc/inline-r-0.7.0.0 --dependency=aeson=aeson-0.8.0.2-85507016086edfeeee941f8a8eed5cd2 --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=bytestring=bytestring-0.10.6.0-6e8453cb70b477776f26900f41a5e17a --dependency=data-default-class=data-default-class-0.0.1-06f131700d8043a79c55259693817561 --dependency=deepseq=deepseq-1.4.1.1-5de90d6c626db2476788444fb08c1eb3 --dependency=exceptions=exceptions-0.8.0.2-b08bd0de7dff383d124cad3f4c34eddd --dependency=mtl=mtl-2.2.1-5cf332b11edb88a6040af20fd6a58acb --dependency=pretty=pretty-1.1.2.0-1d31b75e6aa28069010db3db8ab24535 --dependency=primitive=primitive-0.6-f39f6bcba2f66e648d35c2c6a451ec07 --dependency=process=process-1.2.3.0-36e5501145ab363f58c5e5a7079e9636 --dependency=setenv=setenv-0.1.1.3-d0e7280b0b040f30ae79cbf77c845175 --dependency=singletons=singletons-1.1.2.1-79af6019e5989899d9ed1be7b4536d20 --dependency=template-haskell=template-haskell-2.10.0.0-161ca39a5ae657ff216d049e722e60ea --dependency=text=text-1.2.1.3-2395ef415c1b20175aae83b50060e389 --dependency=th-lift=th-lift-0.7.2-f47e42104ef13446a0b63c1ccb79d01e --dependency=th-orphans=th-orphans-0.12.2-5f347fc4e286f18cfa7cdecfbddd1808 --dependency=transformers=transformers-0.4.2.0-21dcbf13c43f5d8cf6a1f54dee6c5bff --dependency=unix=unix-2.7.1.0-75051e1ddce506fe76a9ea932b926357 --dependency=vector=vector-0.10.12.3-c6e124f63e87ac124e3bbb7bdf0ab89f --extra-include-dirs=/Library/Frameworks/R.framework/Versions/3.2/Resources/lib
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/tcf/.stack/global/.stack-work/logs/inline-r-0.7.0.0.log

    Configuring inline-r-0.7.0.0...
    setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2: The pkg-config package
    'libR' version >=3.0 is required but it could not be found.
```


Hopefully this helps:

```
ls /Library/Frameworks/R.framework/Versions/3.2/Resources/lib/
libR.dylib		libRlapack.dylib	libquadmath.0.dylib
libR.dylib.dSYM		libRlapack.dylib.dSYM	libreadline.5.2.dylib
libRblas.0.dylib	libgcc_s.1.dylib	libreadline.dylib
libRblas.dylib		libgcc_s_x86_64.1.dylib
libRblas.dylib.dSYM	libgfortran.3.dylib
```

**Comment by mboes** [comment] 2015-09-13 19:29
We don't know (need more mac users! ;). @mietek have you had any success installing HaskellR on OS X by any chance? I know you've managed to get previous incarnations to build...

Should we be using `pkg-config` on OS X?

**Comment by mietek** [comment] 2015-09-13 23:19
Using `pkg-config` to locate `libR` should work fine on OS X, as long as `libR.pc` is included in the R installation.  When I worked on this project, I used [Homebrew](http://brew.sh) to install R.

The [`Makefile`](https://github.com/mietek/embed-r/blob/master/Makefile) for [_embed-r_](https://github.com/mietek/embed-r) shows how to ask `pkg-config` for information directly, and how to feed this information to GHC.  Perhaps it’ll be helpful here.

**Comment by michaelochurch** [comment] 2015-09-16 20:15
@mietek Do you have any work-around? This is blocking me from being able to build HaskellR on a Mac?

**Comment by michaelochurch** [comment] 2015-09-16 20:52
Here's an update on this issue I found.

I *think* (this is still unclear) that this issue popped up for me because I installed R manually and didn't end up with ```libR``` in my ```pkg-config``` repository. 

Using Homebrew to put R on my Mac seems to have fixed the problem. Of course, you have to do `brew tap homebrew/science` before you can use Homebrew to install R. 

I'm getting new bugs instead when I try to build (but able to make progress by installing dependencies). So that may be the way out.

**Comment by mboes** [comment] 2015-09-16 21:07
> I'm getting new bugs instead when I try to build (but able to make progress by installing dependencies).

Anything that can be fixed in HaskellR?

**Comment by michaelochurch** [comment] 2015-09-16 21:16
So I installed everything manually (including ZeroMQ) because I couldn't get the dockerized version to work. I'm now getting the error that I've liked in [this Gist](https://gist.github.com/michaelochurch/429ca911f597256d409a). 

It seems (?) to be a problem with some TH calling into R and expecting the R library ```bettertrace``` to be there, and it's not. What makes it weird is that I have ```bettertrace``` installed.

**Comment by thierry-b** [comment] 2015-09-27 15:10
the problem is that the binary R package for OSX doesn't provide the pkg-config file. the problem can be fixed by adding a libR.pc file in /usr/local/lib/pkgconfig containing the following :

rhome=/Library/Frameworks/R.framework
rlibdir=${rhome}/Libraries
rincludedir=${rhome}/Headers

Name: libR
Description: R as a library
Version: 3.2.2
Libs: -L${rlibdir} -lR
Cflags: -I${rincludedir}

**Comment by sbacelar** [comment] 2015-11-06 15:32
I am really having great difficulty to install HaskellR on Mac OSX. I had the same problem with the libR library. I put the libR.pc file indicated by @thierry-b in /usr/local/lib/pkgconfig and then:

```
Configuring inline-r-0.7.0.0...
Warning: This package indirectly depends on multiple versions of the same
package. This is highly likely to cause a compile failure.
package aeson-0.8.0.2 requires mtl-2.2.1
package th-reify-many-0.1.3 requires mtl-2.2.1
package th-orphans-0.12.2 requires mtl-2.2.1
package th-desugar-1.5.4 requires mtl-2.2.1
package singletons-1.1.2.1 requires mtl-2.2.1
package inline-r-0.7.0.0 requires mtl-2.2.1
package exceptions-0.8.0.2 requires mtl-2.2.1
package aeson-0.8.0.2 requires syb-0.5.1
package th-expand-syns-0.3.0.6 requires syb-0.5.1
package th-desugar-1.5.4 requires syb-0.5.1
package scientific-0.3.3.8 requires text-1.2.1.3
package hashable-1.2.3.3 requires text-1.2.1.3
package attoparsec-0.12.1.6 requires text-1.2.1.3
package aeson-0.8.0.2 requires text-1.2.1.3
package inline-r-0.7.0.0 requires text-1.2.1.3
Building inline-r-0.7.0.0...
Preprocessing library inline-r-0.7.0.0...
c2hs: C header contains errors:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/stdlib.h:177:$
  The symbol `__WATCHOS_PROHIBITED' does not fit here.
```

**Comment by mietek** [comment] 2015-11-07 22:08
@sbacelar: Note that is a separate issue.

Most likely, with `c2hs` 0.19.1 or newer, the following part of [`inline-r/cbits/HCompat.h`](https://github.com/tweag/HaskellR/blob/master/inline-r/cbits/Hcompat.h#L10-L24) is no longer helpful, and on OS X 10.11, actively unhelpful:
```
#ifdef H_ARCH_UNIX_DARWIN

/* NOTE: c2hs-0.17.2 and earlier choke on certain OS X system headers:
 * https://github.com/haskell/c2hs/issues/85
 *
 * This file must be #included in every *.chs file which #includes any
 * system header, before all other #includes.
 */

#define __AVAILABILITY__
#define __OSX_AVAILABLE_STARTING(a,b)
#define __OSX_AVAILABLE_BUT_DEPRECATED(a,b,c,d)
#define __OSX_AVAILABLE_BUT_DEPRECATED_MSG(a,b,c,d,e)

#endif /* H_ARCH_UNIX_DARWIN */
```

**Comment by mboes** [comment] 2015-11-17 09:15
The website has been updated to mention explicitly that installation via Homebrew should work and provides instructions for doing so. More importantly, we now have CI setup to check that everything builds just fine on OS X. We don't run tests yet on that platform because what with the lack of dep build caching running tests would push us beyond the Travis CI job time limit. The build uses Homebrew.

So I'm closing this issue. Let's break out the unrelated problem reported by @sbacelar above into a separate issue (there's a fix for that under test).

**Closed** 2015-11-17 10:36 UTC
