### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by bergmark** [tweag/HaskellR#255] opened 2016-07-25 19:48 UTC
From the stackage nightly build:

```
> /tmp/stackage-build8/inline-r-0.9.0.0$ dist/build/test-qq/test-qq
test-qq: R Runtime Error: Error: attempt to apply non-function
```

**Comment by mboes** [comment] 2016-08-08 07:10
I cannot reproduce. Here's what I did:

```
# Run Stackage debian-bootstrap.sh script inside a ubuntu:xenial Docker image
$ stack unpack inline-r
$ cd inline-r-0.9.0.0
$ stack init --resolver nightly
$ stack test
$ echo $?
0
```

Anything I'm missing?

**Comment by bergmark** [comment] 2016-08-27 23:54
Sorry, I'll try to reproduce.

**Comment by mboes** [comment] 2016-08-29 20:53
Closing in favour of #259

**Closed** 2016-08-29 20:56 UTC
