### ISSUE TITLE
Please support for current versions of vector

### ISSUE THREAD

**Issue by peti** [tweag/HaskellR#197] opened 2015-09-07 22:05 UTC
I would like to package `inline-r` on NixOS, but we can't do it right now because we've updated to the latest versions of `vector` a while ago: http://packdeps.haskellers.com/feed?needle=inline-r.

**Comment by Fuuzetsu** [comment] 2015-09-09 21:08
I have something that seems to work, just need to give it a bit of testing tomorrow so expect a fix to this soon.

**Comment by mboes** [comment] 2015-09-13 19:25
@Fuuzetsu status?

**Comment by Fuuzetsu** [comment] 2015-09-14 06:05
The status is that there are changes in https://github.com/tweag/HaskellR/commits/bump-vector that should be good but I am unable to test with docker due to https://github.com/commercialhaskell/stack/issues/974 . So I either PR that and hope for the best for vector-0.11 users with ihaskell or we wait for the stack problem to be resolved.

**Comment by mboes** [comment] 2015-09-21 06:53
@Fuuzetsu reassign to @qnikst to fix tests?

**Comment by Fuuzetsu** [comment] 2015-09-21 07:05
@qnikst My branch has the changes. The issue is that vector-0.11 touches the part of Vector typeclass we just have `error` for and fixing that would require more understanding of how our vector interface is intended to work than I have. Let me know if you need more info about the problem.

**Comment by borsboom** [comment] 2016-01-07 00:28
This also makes inline-r incompatible with Stackage LTS 4.

**Comment by Fuuzetsu** [comment] 2016-01-07 07:55
I was under the impression that inline-r was already out of recent stackage for this reason.

**Comment by mboes** [comment] 2016-01-07 16:20
We already have code in the `new-vector` branch to partially address this, which has proven very difficult given changes in how vector does stream fusion in vector-0.11. I expect to be done with this over the weekend.

**Comment by mboes** [comment] 2016-01-14 09:07
A quick update on the status of this task: mutable vectors API done in the `new-vector` branch, but immutable vector API still not complete. There's a fair amount of wrapper functions to write for that. I'm enslisting @qnikst's assistance on that one.

**Comment by mboes** [comment] 2016-02-01 17:42
This was implemented in #232.

**Closed by mboes** 2016-02-01 17:42 UTC
